#:import Connection views.Connection
#:import Atmospheric views.Atmospheric

ScreenManager:
    Connection:
        id: connection
        on_connect: root.current = 'atmospheric'

    Atmospheric:
        id: atmospheric
        address: connection.address
        rpc_port: connection.rpc_port
        stream_port: connection.stream_port

        on_connection_failure: root.current = 'connection'
